version: "3.8"
services:
  mysql_hesias:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_DATABASE=car_table
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
  pma_hesias:
    image: phpmyadmin/phpmyadmin:5
    restart: always
    ports:
      - 8090:80
    links:
      - mysql_hesias:mysql_hesias
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_ARBITRARY: 1
      PMA_HOST: mysql_hesias